### PR TITLE
Fix calculations for percentage columns width

### LINKED ISSUE #15: Undesired left and rigth paddings in the container
Hello,

Thank you for this great library.

When using the `<StackGrid>` component with both `gutterWidth` and a percentage value in `columnWidth`, the position of the grid items seems incorrect. They are centered in the container leaving an horizontal space at the beginning and the end of it. This space seems to be equal to the number of gutters times the gutter space.

So for instance if I'm using a 4 columns layout with a 10 pixels gutterWidth, I will have a 10×4 = 40px margin on the left and on the right of my container.

### PR DESCRIPTION
**Pull request by mquandalle**
Fixes #15 

Not tested because I'm having some issues when setting `Flow` on my computer, but the logic seems right. Could you please check it out @tsuyoshiwada?

### CODE REVIEW

**Comment by tsuyoshiwada** [comment]
Hi @mquandalle. Thanks for PR and Issues!
This seems to be doing a greatest works.

**Comment by tsuyoshiwada** [comment]
merged.

**Comment by mquandalle** [comment]
As a sidenote I feel the “percentage string” based API isn't the best. I think a very common use case is that have a responsive grid, as suggested in #10, where you have a minimum card width and you try to put as much columns as you can depending on the container width. I think it would be more intuitive to pass the number of columns directly instead of passing a percentage string.

**Comment by tsuyoshiwada** [comment]
That makes sense.
For example, is the following API the ideal?

```javascript
// 4 column
<StackGrid
  column={4}
>
  {items}
</StackGrid>
```

Since we want to keep the `columnWidth` property, we add another `column` property.

**Pull request merged**
