### PR TITLE
horizontal prop

### PR DESCRIPTION
**Pull request by ilyalesik**
Related to https://github.com/tsuyoshiwada/react-stack-grid/issues/25

### CODE REVIEW

**Comment by tsuyoshiwada** [comment]
Hi @ilyalesik. Thank you for contribute :+1:
I confirmed that it is working.

It seems that a Lint error has occurred, please confirm with `$ npm test` and make correction :smiley:

**Comment by ilyalesik** [comment]
Hi, @tsuyoshiwada
There is message
`109:3  error  Prop type `object` is forbidden  react/forbid-prop-types `
StackGrid.js:
109: `style: PropTypes.object,`
I did not change this line in my pull-request.

**Comment by tsuyoshiwada** [comment]
@ilyalesik I am sorry, I missed it ... :scream:
There is an error similarly in `master`. Since I will fix it, there is no problem with PR!
Thanks.

**Comment by ilyalesik** [comment]
Thanks!

**Comment by tsuyoshiwada** [comment]
@ilyalesik Released as v0.5.0 :tada:

**Comment by ilyalesik** [comment]
That's great!
I think in the future it will be possible to implement different distribution (order) of elements with 'strategy' pattern. 
There could be a parameter `distribution` for StackGrid component, function like this:
`([{height, ...},...], maxColumn) => [{top, left, width, height},...]`
It would be two options "out of the box" - `import {DefaultDistribution, HorizontalDistribution} from 'react-stack-grid'`.
This would allow developers to customize the order more flexibly.

**Comment by tsuyoshiwada** [comment]
@ilyalesik It looks like a good idea!
PR is always welcome :smile:

**Pull request merged**
