### PR TITLE
Make transform coordinates round to the nearest integer to avoid blur

### LINKED ISSUE #37: round translate coordinates to avoid blurriness
sometimes the transforms end up being non integer pixels (e.g. transformX: 117.5px), which results in blurry pixels in chrome. could the transform final value be rounded to the nearest whole pixel coordinate to avoid this?

### PR DESCRIPTION
**Pull request by xaviergonz**
Fixes #37

### CODE REVIEW

**Comment by tsuyoshiwada** [comment]
Hi @xaviergonz Thank you for Contributing!!

It is likely to be merged if you can modify the test code according to the change :smile:

**Comment by xaviergonz** [comment]
@tsuyoshiwada tests fixed :)

**Comment by tsuyoshiwada** [comment]
@xaviergonz I'm sorry that the response was delayed... :sob:
merged.

**Comment by tsuyoshiwada** [comment]
@xaviergonz Released as `v0.7.1` :tada:

**Pull request merged**
